version: '3'
services:
  keystone:
    image: jdtzmn/keystone-docker
    environment:
      - HOSTNAME=keystone
      - KEYSTONE_ADMIN_PASSWORD=secret
  horizon:
    build: .
    environment:
      - FLOCX_API_HOST=http://host.docker.internal
      - TOX_TESTENV_PASSENV=KEYSTONE_HOST FLOCX_*
    volumes: 
      - .:/flocx-ui
    ports:
        - "8000:80"