version: '3'
services:
  baremetal:
    build: ./docker/baremetal_mock
    volumes: 
      - ./docker/baremetal_mock:/usr/src/app
  horizon:
    build: .
    environment:
      - KEYSTONE_HOST=host.docker.internal
      - FLOCX_API_HOST=http://host.docker.internal
      - TOX_TESTENV_PASSENV=KEYSTONE_HOST FLOCX_*
    volumes: 
      - .:/flocx-ui
    ports:
        - "8000:80"
